### ISSUE TITLE
xcube mis-computes cube extends whith reversed bnds coordinates

### ISSUE THREAD

**Issue by dzelge** [dcs4cop/xcube#232]
**Describe the issue**

When visualising cubes (in e.g. xcube viewer), xcube uses bnds coordinates to determine resolutions during tile computations. xcube uses e.g. lat_bnds[0, 0] and lat_bnds[0, -1] as input to get the full extent of the cube. In some cases, the bnds are in reverse order which results in a miscomputation of the extent and subsequently of tile resolutions.

**To Reproduce**
1. Use ESDC v2.0.0 with 0.0833deg resolution
2. Calculate extent using xcube (see below Norma's comment)

**Expected behavior**

Either xcube does not allow such bnds coordinates or uses the correct elements of the bnds arrays for compurting the cube's extent.

**Additional context**

Refer to #90 

> I believe, I have an explanation now: For the ESDL cube, xcube server reports an geographical extent of `lon1=-180, lat1=-89.75, lon2=180, lat2=89.75`. These are the values extracted from `lon_bnds` and `lat_bnds` of the cube. The latitudes don't look ok to me, they should be `lat1=-90, lat2=90`.
> 
> For the layer display, the image's spatial resolution is required. In xcube server, it is currently computed as `(lat2 - lat1) / image_height`. For an image of size 1440 x 720 this discrepancy sums up to one degree in longitude-direction.

**Comment by forman** [comment]
Ok, `xcube` code is fine because it follows [CF Conventions](http://cfconventions.org/Data/cf-conventions/cf-conventions-1.7/cf-conventions.html#cell-boundaries):

> for an increasing coordinate, lat(1) > lat(0) implies latbnd(i,1) >= latbnd(i,0) for all i

which implies that

* for a **decreasing** coordinate, lat(1) **<** lat(0) implies latbnd(i,1) **<=** latbnd(i,0) for all i

According to this definition, the ESDL latitude bounds coordinate `lat_bnds` is wrongly filled.

However, I will make `xcube` more tolerant w.r.t. to such minor inconsistencies with CF.
