### ISSUE TITLE
Allow for GDAL >= 3

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#348]
Current env is restricted to outdated GDAL < 3.

- [x] Inform related people from https://gitext.sinergise.com/dcfs/common/-/issues/224

**Comment by pont-us** [comment]
What restricts the current environment to GDAL <3? Since commit c1175bee on 2020-03-18, the specification in `environment.yml` is `gdal >=2.4`. It's still restricted to <3 in the conda-forge `meta.yaml` file, but I have a [pull request](https://github.com/conda-forge/xcube-feedstock/pull/11) pending to fix this -- currently in draft mode because I'm waiting for feedback, in part precisely on whether it's safe to remove the GDAL restriction.

The current `environment.yml` does, admittedly, produce an environment with GDAL 2.4.3. But I assume that this must be due to a restriction in some transitive dependency, since xcube's `environment.yml` doesn't include this restriction.

**Comment by forman** [comment]
In xcube 0.6:

    - gdal >= 3.0

**Comment by pont-us** [comment]
Fixed in commit a3abcceab134.

**Comment by forman** [comment]
Will be available in xcube 0.6

**Comment by pont-us** [comment]
Currently, xcube is compatible with GDAL >=3.0, but not with GDAL >=3.1. See Issue #375 .
