### ISSUE TITLE
Address `xcube serve`  FutureWarning: timezone-naive DatetimeIndex with a timezone-aware datetime is deprecated

### ISSUE THREAD

**Issue by AliceBalfanz** [dcs4cop/xcube#555]
When serving xcube datasets with `xcube serve` there is a 
`FutureWarning: Indexing a timezone-naive DatetimeIndex with a timezone-aware datetime is deprecated and will raise KeyError in a future version.  Use a timezone-naive object instead.`
We need to address this before we run into that KeyError.

**Comment by pont-us** [comment]
The warning has now evolved into an error:

```
TypeError: Cannot compare dtypes datetime64[ns] and datetime64[ns, UTC]
```

[traceback.txt](https://github.com/dcs4cop/xcube/files/7987730/traceback.txt)

**Comment by pont-us** [comment]
I suspect that the root cause is the dataset being served, which has a timezone-naive `datetime64` time dimension but timezone-aware co-ordinate values. That probably shouldn't happen, but needs to be handled gracefully when it does. The linked pull request makes a check just before the `sel` call which triggers the error and applies a workaround, but if the dataset co-ordinate values are indeed the culprit we should probably also check for this problem at an earlier stage and issue a warning and/or reject the dataset.
