### ISSUE TITLE
Numerous TypeErrors on python 3.8

### ISSUE THREAD

**Issue by TonioF** [dcs4cop/xcube#760]
When xcube is run in an environment with python 3.8, during loading of many packages you will see an error of the form: TypeError: '...' object is not subscriptable. You can see this when you run xcube tests, of which at the time of writing 70 fail (see here: https://github.com/dcs4cop/xcube/actions/runs/3394383062/jobs/5642874415).

One solution to this problem would be to set python 3.9 as the minimum version. This has been proposed in #747.

**Comment by pont-us** [comment]
On a quick look, most or all of the errors seem to be caused by use of generic type hinting with standard collections per [PEP 585](https://peps.python.org/pep-0585/) -- e.g. `list[str]` rather than the older `List[str]` (with `List` imported from `typing`). The new syntax is only supported from Python 3.9, and the old syntax is deprecated; in many cases `from __future__ import annotations` enables it for 3.7 and 3.8, but I think pytest is doing some clever runtime type introspection which the `__future__` import doesn't support. So in short I think our options are:

1. Change all `list[str]`-style annotations to `List[str]`-style ones. Then change them all back again in ~2 years when the deprecated syntax is dropped completely (and stop supporting Python 3.8 at that point).
2. Require Python 3.9 as minimum, as proposed above.

Unless we have a specific need to support Python 3.8, option 2 seems preferable to me.
