### ISSUE TITLE
Deploy xcube conda package

### ISSUE THREAD

**Issue by forman** [dcs4cop/xcube#98]
**Is your feature request related to a problem? Please describe.**

We still have no deployed xcube conda package.  

**Describe the solution you'd like**

- [x] Create `xcube-conda` repo with `recipe/*`.
- [x] Configure Travis 
    - [x]  build
    - [x] test 
    - [x] deploy on conda-forge channel.

**EDIT**

- [x] Rename version to `0.2.0.dev`

**Comment by dzelge** [comment]
PR awaiting on xcube-conda

**Comment by forman** [comment]
Find my comments there...

**Comment by dzelge** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Publish xcube on conda-forge](https://trello.com/c/xkKBiKYy/46-publish-xcube-on-conda-forge)

**Comment by dzelge** [comment]
The conda build recipe has been reviewed on conda forge. The following needs to be addressed:

- Dependency versions are too pinned down
- We shall use matplotlib-base if we don't use Qt
- They would like to see a less pinned down python version (at least 3.6 and future 3.8)

My suggestions therefore:

- We shoud consider adapting our xcube travis to test for python versions 3.6 and 3.7. A good recipe is [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html)
- Many versions should be a range rather than an explicit version number
- Can we use matplotlib-base?

**Comment by forman** [comment]
@dzelge, please also create a PR for the `environment.yml` in `xcube`.

**Comment by forman** [comment]
@dzelge , please mention in xcube CHANGELOG, then close this one.
